import { useMemo, useState } from 'react';
import { PageHeader } from '../components/ui/PageHeader';
import { label, relativeTime, useWorkspaceData } from '../features/workspace/WorkspaceDataContext';

export function AlertsPage() {
  const { alerts, loading, actionLoading, error, runAction } = useWorkspaceData();
  const [term, setTerm] = useState(''); const [severity, setSeverity] = useState(''); const [status, setStatus] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => alerts.filter((alert) => (!term || `${alert.title} ${alert.sourceIp}`.toLowerCase().includes(term.toLowerCase())) && (!severity || alert.severity === severity) && (!status || alert.status === status)), [alerts, term, severity, status]);
  const selected = alerts.find((alert) => alert.$id === selectedId);
  return <><PageHeader title="Alerts" description="Tinjau alert keamanan sintetis di workspace Anda." action={<button className="primary-button" type="button" disabled={actionLoading} onClick={() => void runAction({ action: 'generate-alert' })}>{actionLoading ? 'Generating…' : 'Generate simulated alert'}</button>} /><article className="panel"><div className="filter-row"><input value={term} onChange={(event) => setTerm(event.target.value)} aria-label="Cari alert" placeholder="Cari alert atau source IP…" /><select value={severity} onChange={(event) => setSeverity(event.target.value)} aria-label="Filter severity"><option value="">Semua severity</option>{['critical', 'high', 'medium', 'low'].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter status"><option value="">Semua status</option>{['new', 'triaged', 'dismissed'].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></div>{loading ? <p className="data-state">Memuat alerts…</p> : error ? <p className="data-state error-message">{error}</p> : <div className="table-wrap"><table><thead><tr><th>ID</th><th>Alert</th><th>Severity</th><th>Status</th><th>Source IP</th><th>Waktu</th></tr></thead><tbody>{filtered.map((alert) => <tr key={alert.$id} className="clickable-row" onClick={() => setSelectedId(alert.$id)}><td><code>{alert.$id.slice(0, 8)}</code></td><td><strong>{alert.title}</strong></td><td><span className={`severity severity-${alert.severity}`}>{label(alert.severity)}</span></td><td>{label(alert.status)}</td><td><code>{alert.sourceIp}</code></td><td>{relativeTime(alert.simulatedAt)}</td></tr>)}{filtered.length === 0 && <tr><td colSpan={6}>Tidak ada alert yang sesuai.</td></tr>}</tbody></table></div>}</article>{selected && <article className="panel detail-panel"><div className="panel-heading"><div><h3>{selected.title}</h3><p>Detail alert sintetis</p></div><button className="text-button" onClick={() => setSelectedId(null)}>Tutup</button></div><dl><div><dt>Severity</dt><dd><span className={`severity severity-${selected.severity}`}>{label(selected.severity)}</span></dd></div><div><dt>Status</dt><dd>{label(selected.status)}</dd></div><div><dt>Source IP</dt><dd><code>{selected.sourceIp}</code></dd></div><div><dt>Deskripsi</dt><dd>{selected.description}</dd></div><div><dt>Simulated at</dt><dd>{relativeTime(selected.simulatedAt)}</dd></div></dl></article>}</>;
}
