import { useState, type FormEvent } from 'react';
import { PageHeader } from '../components/ui/PageHeader';
import { label, relativeTime, useWorkspaceData } from '../features/workspace/WorkspaceDataContext';

const columns = ['new', 'investigating', 'resolved'];
export function IncidentsPage() {
  const { incidents, notes, loading, actionLoading, error, runAction } = useWorkspaceData(); const [selectedId, setSelectedId] = useState<string | null>(null); const [noteBody, setNoteBody] = useState('');
  const selected = incidents.find((incident) => incident.$id === selectedId); const selectedNotes = notes.filter((note) => note.incidentId === selectedId);
  const submitNote = (event: FormEvent) => { event.preventDefault(); if (!selected || !noteBody.trim()) return; void runAction({ action: 'add-note', incidentId: selected.$id, body: noteBody.trim() }).then(() => setNoteBody('')); };
  return <><PageHeader title="Incidents" description="Kelola proses investigasi dari alert hingga resolusi." />
    {loading ? <p className="data-state">Memuat incidents…</p> : error ? <p className="data-state error-message">{error}</p> : <section className="incident-board">{columns.map((status) => { const items = incidents.filter((incident) => incident.status === status); return <div className="board-column" key={status}><div className="board-heading"><h3>{label(status)}</h3><span>{items.length}</span></div>{items.map((incident) => <article className="incident-card" key={incident.$id}><div><code>{incident.$id.slice(0, 8)}</code><span className={`severity severity-${incident.priority}`}>{label(incident.priority)}</span></div><h4>{incident.summary}</h4><small>Updated {relativeTime(incident.updatedAt)}</small><label className="incident-action">Status<select value={incident.status} disabled={actionLoading} onChange={(event) => void runAction({ action: 'update-incident', incidentId: incident.$id, status: event.target.value })}>{columns.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><button className="text-button" onClick={() => setSelectedId(incident.$id)}>Detail & notes</button></article>)}</div>; })}</section>}
    {selected && <article className="panel detail-panel"><div className="panel-heading"><div><h3>{selected.summary}</h3><p>Incident detail dan catatan investigasi</p></div><button className="text-button" onClick={() => setSelectedId(null)}>Tutup</button></div><dl><div><dt>Priority</dt><dd><span className={`severity severity-${selected.priority}`}>{label(selected.priority)}</span></dd></div><div><dt>Status</dt><dd>{label(selected.status)}</dd></div><div><dt>Updated</dt><dd>{relativeTime(selected.updatedAt)}</dd></div></dl><div className="notes-section"><h4>Catatan investigasi</h4>{selectedNotes.length ? selectedNotes.map((note) => <div className="note" key={note.$id}><p>{note.body}</p><small>{relativeTime(note.createdAt)}</small></div>) : <p className="empty-copy">Belum ada catatan.</p>}<form onSubmit={submitNote}><textarea value={noteBody} maxLength={2000} onChange={(event) => setNoteBody(event.target.value)} placeholder="Tambahkan catatan investigasi sintetis…" /><button className="primary-button" disabled={actionLoading} type="submit">Simpan catatan</button></form></div></article>}</>;
}
