import { PageHeader } from '../components/ui/PageHeader';
import { relativeTime, useWorkspaceData } from '../features/workspace/WorkspaceDataContext';

export function NotificationsPage() {
  const { notifications, loading, error } = useWorkspaceData();
  return <><PageHeader title="Notifications" description="Pratinjau notifikasi simulasi—tidak ada pesan yang dikirim ke Telegram." /><div className="notification-notice"><strong>Telegram simulation only</strong><span>Konten dibuat dari data sintetis dan hanya ditampilkan di browser.</span></div>
    <section className="phone-preview"><div className="phone-header"><span className="brand-mark">S</span><div><strong>Sentinel Alert Bot</strong><small>simulation</small></div></div>{loading ? <p className="data-state">Memuat notifikasi…</p> : error ? <p className="data-state error-message">{error}</p> : notifications.map((notification) => <div className="message" key={notification.$id}><strong>{notification.message?.startsWith('🚨') ? '🚨 Critical security alert' : 'Incident updated'}</strong><p>{notification.message}</p><small>{relativeTime(notification.createdAt)}</small></div>)}</section>
    <article className="panel telegram-guide"><div className="panel-heading"><div><h3>Telegram integration guide</h3><p>Referensi integrasi produksi—tidak aktif pada dashboard demo ini.</p></div></div><p>Gunakan proyek bot Wazuh–Telegram sebagai referensi operasional terpisah. Dashboard demo tidak menyimpan token Telegram, tidak membuka koneksi bot, dan tidak meneruskan alert sintetis ke Telegram.</p><ol><li>Buat lingkungan produksi terpisah; jangan gunakan data atau API key demo.</li><li>Simpan token bot dan konfigurasi Wazuh sebagai secret pada worker/Function server-side.</li><li>Kirim hanya alert yang telah dinormalisasi dan disaring; jangan mengirim raw log atau kredensial.</li><li>Aktifkan audit, rate limiting, dan daftar chat tujuan yang diizinkan.</li></ol><p><a href="https://github.com/amri134/wazuh-on-telegram" target="_blank" rel="noreferrer">Buka repository Wazuh on Telegram ↗</a></p></article></>;
}
